### ISSUE TITLE
Duda Tarea DCClue

### ISSUE THREAD

**Issue by Mario-uc** [IIC2613-Inteligencia-Artificial-2022-1/Tarea-1#1]
¿Se asume que todos dan su versión de donde estuvo cada persona en cada tiempo? ¿o pueden no decirlo?

**Comment by FeBalla** [comment]
No estamos respondiendo dudas en este repositorio. Por favor, hacer las dudas en el [Syllabus](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Syllabus/issues)
