### ISSUE TITLE
¿Como funciona el #minimize?

### ISSUE THREAD

**Issue by Mario-uc** [IIC2613-Inteligencia-Artificial-2022-1/Tarea-1#2]
Recuerdo que en la ayudantía lo mencionaron muy por encima, pero me quedaron muchas dudas de como se usa .

**Comment by FeBalla** [comment]
No estamos respondiendo dudas en este repositorio. Por favor, hacer las dudas en el [Syllabus](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Syllabus/issues)
