### ISSUE TITLE
Duda Culpable - DCClue

### ISSUE THREAD

**Issue by anais-mv** [IIC2613-Inteligencia-Artificial-2022-1/Tarea-1#3]
Hola! el culpable debe mentir siempre? o puede decir la verdad a veces para confundir?

**Comment by FeBalla** [comment]
No estamos respondiendo dudas en este repositorio. Por favor, hacer las dudas en el [Syllabus](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Syllabus/issues)
