### ISSUE TITLE
Duda Cajas - DCCajas

### ISSUE THREAD

**Issue by anais-mv** [IIC2613-Inteligencia-Artificial-2022-1/Tarea-1#4]
Hola! el robot sólo puede tomar la caja estando ya en el espacio de la caja? o si el robot está atrás de la caja por ejemplo la puede tomar y ahora la caja está en la misma posición que el robot? (en este caso Y-1)

**Comment by FeBalla** [comment]
No estamos respondiendo dudas en este repositorio. Por favor, hacer las dudas en el [Syllabus](https://github.com/IIC2613-Inteligencia-Artificial-2022-1/Syllabus/issues)
